# Merapikan folder src kedua frontend supaya SAMA PERSIS dengan repo (setelah commit 12).
#  1. Memperbaiki nama file yang beda huruf besar/kecil (mis. stockChart.vue -> StockChart.vue).
#     Windows tidak membedakan huruf besar/kecil, tapi vue-tsc dan server Linux (Portainer) membedakannya.
#  2. Memindahkan file lama yang tidak ada di repo (mock service, PlaceholderPage, dll.)
#     ke folder cadangan di %TEMP% (bukan dihapus permanen).
#
# Jalankan dari root repo (folder yang berisi frontend-admin dan frontend-kasir):
#   powershell -ExecutionPolicy Bypass -File .\rapikan-frontend.ps1           # hanya menampilkan rencana
#   powershell -ExecutionPolicy Bypass -File .\rapikan-frontend.ps1 -Apply    # benar-benar menjalankan
param([switch]$Apply)
$ErrorActionPreference = 'Stop'
if (-not (Test-Path 'frontend-admin/src') -or -not (Test-Path 'frontend-kasir/src')) {
  Write-Error 'Jalankan dari root repo KOPMAN.'; exit 1
}
$expected = @(
  'frontend-admin/src/App.vue',
  'frontend-admin/src/components/charts/BestSellerChart.vue',
  'frontend-admin/src/components/charts/CashflowChart.vue',
  'frontend-admin/src/components/charts/ChartCard.vue',
  'frontend-admin/src/components/charts/ForecastChart.vue',
  'frontend-admin/src/components/charts/GrossProfitChart.vue',
  'frontend-admin/src/components/charts/PeriodPicker.vue',
  'frontend-admin/src/components/charts/StockChart.vue',
  'frontend-admin/src/components/charts/StockoutRiskChart.vue',
  'frontend-admin/src/components/charts/setup.ts',
  'frontend-admin/src/components/common/ActiveBadge.vue',
  'frontend-admin/src/components/common/BarcodeInput.vue',
  'frontend-admin/src/components/common/BarcodeScanner.vue',
  'frontend-admin/src/components/common/BrandMark.vue',
  'frontend-admin/src/components/common/ConfirmModal.vue',
  'frontend-admin/src/components/common/ErrorAlert.vue',
  'frontend-admin/src/components/common/FilterToggle.vue',
  'frontend-admin/src/components/common/Modal.vue',
  'frontend-admin/src/components/common/PageHeader.vue',
  'frontend-admin/src/components/common/PagePagination.vue',
  'frontend-admin/src/components/common/SearchInput.vue',
  'frontend-admin/src/components/common/StatCard.vue',
  'frontend-admin/src/components/common/StockBadge.vue',
  'frontend-admin/src/components/common/ThemeToggle.vue',
  'frontend-admin/src/components/common/UserMenu.vue',
  'frontend-admin/src/components/form/FormField.vue',
  'frontend-admin/src/components/insights/AssociationRulesCard.vue',
  'frontend-admin/src/components/insights/ForecastDialog.vue',
  'frontend-admin/src/components/layout/AppSidebar.vue',
  'frontend-admin/src/components/layout/AppTopbar.vue',
  'frontend-admin/src/components/table/DataTable.vue',
  'frontend-admin/src/components/table/TablePagination.vue',
  'frontend-admin/src/components/table/types.ts',
  'frontend-admin/src/components/ui/alert-dialog/AlertDialog.vue',
  'frontend-admin/src/components/ui/alert-dialog/AlertDialogAction.vue',
  'frontend-admin/src/components/ui/alert-dialog/AlertDialogCancel.vue',
  'frontend-admin/src/components/ui/alert-dialog/AlertDialogContent.vue',
  'frontend-admin/src/components/ui/alert-dialog/AlertDialogDescription.vue',
  'frontend-admin/src/components/ui/alert-dialog/AlertDialogFooter.vue',
  'frontend-admin/src/components/ui/alert-dialog/AlertDialogHeader.vue',
  'frontend-admin/src/components/ui/alert-dialog/AlertDialogTitle.vue',
  'frontend-admin/src/components/ui/alert-dialog/AlertDialogTrigger.vue',
  'frontend-admin/src/components/ui/alert-dialog/index.ts',
  'frontend-admin/src/components/ui/alert/Alert.vue',
  'frontend-admin/src/components/ui/alert/AlertDescription.vue',
  'frontend-admin/src/components/ui/alert/AlertTitle.vue',
  'frontend-admin/src/components/ui/alert/index.ts',
  'frontend-admin/src/components/ui/avatar/Avatar.vue',
  'frontend-admin/src/components/ui/avatar/AvatarFallback.vue',
  'frontend-admin/src/components/ui/avatar/AvatarImage.vue',
  'frontend-admin/src/components/ui/avatar/index.ts',
  'frontend-admin/src/components/ui/badge/Badge.vue',
  'frontend-admin/src/components/ui/badge/index.ts',
  'frontend-admin/src/components/ui/button/Button.vue',
  'frontend-admin/src/components/ui/button/index.ts',
  'frontend-admin/src/components/ui/card/Card.vue',
  'frontend-admin/src/components/ui/card/CardAction.vue',
  'frontend-admin/src/components/ui/card/CardContent.vue',
  'frontend-admin/src/components/ui/card/CardDescription.vue',
  'frontend-admin/src/components/ui/card/CardFooter.vue',
  'frontend-admin/src/components/ui/card/CardHeader.vue',
  'frontend-admin/src/components/ui/card/CardTitle.vue',
  'frontend-admin/src/components/ui/card/index.ts',
  'frontend-admin/src/components/ui/dialog/Dialog.vue',
  'frontend-admin/src/components/ui/dialog/DialogClose.vue',
  'frontend-admin/src/components/ui/dialog/DialogContent.vue',
  'frontend-admin/src/components/ui/dialog/DialogDescription.vue',
  'frontend-admin/src/components/ui/dialog/DialogFooter.vue',
  'frontend-admin/src/components/ui/dialog/DialogHeader.vue',
  'frontend-admin/src/components/ui/dialog/DialogOverlay.vue',
  'frontend-admin/src/components/ui/dialog/DialogScrollContent.vue',
  'frontend-admin/src/components/ui/dialog/DialogTitle.vue',
  'frontend-admin/src/components/ui/dialog/DialogTrigger.vue',
  'frontend-admin/src/components/ui/dialog/index.ts',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenu.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuContent.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuGroup.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuItem.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuLabel.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuRadioItem.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuSeparator.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuShortcut.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuSub.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuSubContent.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue',
  'frontend-admin/src/components/ui/dropdown-menu/DropdownMenuTrigger.vue',
  'frontend-admin/src/components/ui/dropdown-menu/index.ts',
  'frontend-admin/src/components/ui/empty/Empty.vue',
  'frontend-admin/src/components/ui/empty/EmptyContent.vue',
  'frontend-admin/src/components/ui/empty/EmptyDescription.vue',
  'frontend-admin/src/components/ui/empty/EmptyHeader.vue',
  'frontend-admin/src/components/ui/empty/EmptyMedia.vue',
  'frontend-admin/src/components/ui/empty/EmptyTitle.vue',
  'frontend-admin/src/components/ui/empty/index.ts',
  'frontend-admin/src/components/ui/field/Field.vue',
  'frontend-admin/src/components/ui/field/FieldContent.vue',
  'frontend-admin/src/components/ui/field/FieldDescription.vue',
  'frontend-admin/src/components/ui/field/FieldError.vue',
  'frontend-admin/src/components/ui/field/FieldGroup.vue',
  'frontend-admin/src/components/ui/field/FieldLabel.vue',
  'frontend-admin/src/components/ui/field/FieldLegend.vue',
  'frontend-admin/src/components/ui/field/FieldSeparator.vue',
  'frontend-admin/src/components/ui/field/FieldSet.vue',
  'frontend-admin/src/components/ui/field/FieldTitle.vue',
  'frontend-admin/src/components/ui/field/index.ts',
  'frontend-admin/src/components/ui/input/Input.vue',
  'frontend-admin/src/components/ui/input/index.ts',
  'frontend-admin/src/components/ui/label/Label.vue',
  'frontend-admin/src/components/ui/label/index.ts',
  'frontend-admin/src/components/ui/native-select/NativeSelect.vue',
  'frontend-admin/src/components/ui/native-select/NativeSelectOptGroup.vue',
  'frontend-admin/src/components/ui/native-select/NativeSelectOption.vue',
  'frontend-admin/src/components/ui/native-select/index.ts',
  'frontend-admin/src/components/ui/pagination/Pagination.vue',
  'frontend-admin/src/components/ui/pagination/PaginationContent.vue',
  'frontend-admin/src/components/ui/pagination/PaginationEllipsis.vue',
  'frontend-admin/src/components/ui/pagination/PaginationFirst.vue',
  'frontend-admin/src/components/ui/pagination/PaginationItem.vue',
  'frontend-admin/src/components/ui/pagination/PaginationLast.vue',
  'frontend-admin/src/components/ui/pagination/PaginationNext.vue',
  'frontend-admin/src/components/ui/pagination/PaginationPrevious.vue',
  'frontend-admin/src/components/ui/pagination/index.ts',
  'frontend-admin/src/components/ui/separator/Separator.vue',
  'frontend-admin/src/components/ui/separator/index.ts',
  'frontend-admin/src/components/ui/sheet/Sheet.vue',
  'frontend-admin/src/components/ui/sheet/SheetClose.vue',
  'frontend-admin/src/components/ui/sheet/SheetContent.vue',
  'frontend-admin/src/components/ui/sheet/SheetDescription.vue',
  'frontend-admin/src/components/ui/sheet/SheetFooter.vue',
  'frontend-admin/src/components/ui/sheet/SheetHeader.vue',
  'frontend-admin/src/components/ui/sheet/SheetOverlay.vue',
  'frontend-admin/src/components/ui/sheet/SheetTitle.vue',
  'frontend-admin/src/components/ui/sheet/SheetTrigger.vue',
  'frontend-admin/src/components/ui/sheet/index.ts',
  'frontend-admin/src/components/ui/sidebar/Sidebar.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarContent.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarFooter.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarGroup.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarGroupAction.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarGroupContent.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarGroupLabel.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarHeader.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarInput.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarInset.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarMenu.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarMenuAction.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarMenuBadge.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarMenuButton.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarMenuButtonChild.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarMenuItem.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarMenuSkeleton.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarMenuSub.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarMenuSubButton.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarMenuSubItem.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarProvider.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarRail.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarSeparator.vue',
  'frontend-admin/src/components/ui/sidebar/SidebarTrigger.vue',
  'frontend-admin/src/components/ui/sidebar/index.ts',
  'frontend-admin/src/components/ui/sidebar/utils.ts',
  'frontend-admin/src/components/ui/skeleton/Skeleton.vue',
  'frontend-admin/src/components/ui/skeleton/index.ts',
  'frontend-admin/src/components/ui/sonner/Sonner.vue',
  'frontend-admin/src/components/ui/sonner/index.ts',
  'frontend-admin/src/components/ui/spinner/Spinner.vue',
  'frontend-admin/src/components/ui/spinner/index.ts',
  'frontend-admin/src/components/ui/switch/Switch.vue',
  'frontend-admin/src/components/ui/switch/index.ts',
  'frontend-admin/src/components/ui/table/Table.vue',
  'frontend-admin/src/components/ui/table/TableBody.vue',
  'frontend-admin/src/components/ui/table/TableCaption.vue',
  'frontend-admin/src/components/ui/table/TableCell.vue',
  'frontend-admin/src/components/ui/table/TableEmpty.vue',
  'frontend-admin/src/components/ui/table/TableFooter.vue',
  'frontend-admin/src/components/ui/table/TableHead.vue',
  'frontend-admin/src/components/ui/table/TableHeader.vue',
  'frontend-admin/src/components/ui/table/TableRow.vue',
  'frontend-admin/src/components/ui/table/index.ts',
  'frontend-admin/src/components/ui/tabs/Tabs.vue',
  'frontend-admin/src/components/ui/tabs/TabsContent.vue',
  'frontend-admin/src/components/ui/tabs/TabsList.vue',
  'frontend-admin/src/components/ui/tabs/TabsTrigger.vue',
  'frontend-admin/src/components/ui/tabs/index.ts',
  'frontend-admin/src/components/ui/textarea/Textarea.vue',
  'frontend-admin/src/components/ui/textarea/index.ts',
  'frontend-admin/src/components/ui/toggle-group/ToggleGroup.vue',
  'frontend-admin/src/components/ui/toggle-group/ToggleGroupItem.vue',
  'frontend-admin/src/components/ui/toggle-group/index.ts',
  'frontend-admin/src/components/ui/toggle/Toggle.vue',
  'frontend-admin/src/components/ui/toggle/index.ts',
  'frontend-admin/src/components/ui/tooltip/Tooltip.vue',
  'frontend-admin/src/components/ui/tooltip/TooltipContent.vue',
  'frontend-admin/src/components/ui/tooltip/TooltipProvider.vue',
  'frontend-admin/src/components/ui/tooltip/TooltipTrigger.vue',
  'frontend-admin/src/components/ui/tooltip/index.ts',
  'frontend-admin/src/composables/useChartTheme.ts',
  'frontend-admin/src/composables/usePagination.ts',
  'frontend-admin/src/composables/useScannerInput.ts',
  'frontend-admin/src/composables/useTheme.ts',
  'frontend-admin/src/composables/useToast.ts',
  'frontend-admin/src/env.d.ts',
  'frontend-admin/src/layouts/DashboardLayout.vue',
  'frontend-admin/src/lib/utils.ts',
  'frontend-admin/src/main.ts',
  'frontend-admin/src/pages/admin/AiEnginePage.vue',
  'frontend-admin/src/pages/admin/AuditLogsPage.vue',
  'frontend-admin/src/pages/admin/MembersPage.vue',
  'frontend-admin/src/pages/admin/UsersPage.vue',
  'frontend-admin/src/pages/auth/LoginPage.vue',
  'frontend-admin/src/pages/dashboard/DashboardPage.vue',
  'frontend-admin/src/pages/errors/ForbiddenPage.vue',
  'frontend-admin/src/pages/errors/NotFoundPage.vue',
  'frontend-admin/src/pages/logistik/CategoriesPage.vue',
  'frontend-admin/src/pages/logistik/ProductFormPage.vue',
  'frontend-admin/src/pages/logistik/ProductsPage.vue',
  'frontend-admin/src/pages/logistik/RestockDetailPage.vue',
  'frontend-admin/src/pages/logistik/RestockFormPage.vue',
  'frontend-admin/src/pages/logistik/RestocksPage.vue',
  'frontend-admin/src/pages/logistik/StockPage.vue',
  'frontend-admin/src/pages/logistik/SuppliersPage.vue',
  'frontend-admin/src/pages/owner/ReportsPage.vue',
  'frontend-admin/src/pages/owner/TransactionBody.vue',
  'frontend-admin/src/pages/owner/TransactionDetailPage.vue',
  'frontend-admin/src/pages/owner/TransactionsPage.vue',
  'frontend-admin/src/router/index.ts',
  'frontend-admin/src/router/routes.ts',
  'frontend-admin/src/services/api.ts',
  'frontend-admin/src/services/apiClient.ts',
  'frontend-admin/src/stores/auth.ts',
  'frontend-admin/src/style.css',
  'frontend-admin/src/types/api.ts',
  'frontend-admin/src/utils/format.ts',
  'frontend-admin/src/utils/insight.ts',
  'frontend-kasir/src/App.vue',
  'frontend-kasir/src/components/cart/CartPanel.vue',
  'frontend-kasir/src/components/cart/CartSuggestions.vue',
  'frontend-kasir/src/components/common/BarcodeScanner.vue',
  'frontend-kasir/src/components/common/BrandMark.vue',
  'frontend-kasir/src/components/common/PagePagination.vue',
  'frontend-kasir/src/components/common/ThemeToggle.vue',
  'frontend-kasir/src/components/common/UserMenu.vue',
  'frontend-kasir/src/components/invoice/InvoiceView.vue',
  'frontend-kasir/src/components/payment/CashPanel.vue',
  'frontend-kasir/src/components/payment/MemberLookup.vue',
  'frontend-kasir/src/components/payment/MemberRegisterDialog.vue',
  'frontend-kasir/src/components/payment/QrisPanel.vue',
  'frontend-kasir/src/components/product/ProductCard.vue',
  'frontend-kasir/src/components/ui/alert/Alert.vue',
  'frontend-kasir/src/components/ui/alert/AlertDescription.vue',
  'frontend-kasir/src/components/ui/alert/AlertTitle.vue',
  'frontend-kasir/src/components/ui/alert/index.ts',
  'frontend-kasir/src/components/ui/avatar/Avatar.vue',
  'frontend-kasir/src/components/ui/avatar/AvatarFallback.vue',
  'frontend-kasir/src/components/ui/avatar/AvatarImage.vue',
  'frontend-kasir/src/components/ui/avatar/index.ts',
  'frontend-kasir/src/components/ui/badge/Badge.vue',
  'frontend-kasir/src/components/ui/badge/index.ts',
  'frontend-kasir/src/components/ui/button/Button.vue',
  'frontend-kasir/src/components/ui/button/index.ts',
  'frontend-kasir/src/components/ui/card/Card.vue',
  'frontend-kasir/src/components/ui/card/CardAction.vue',
  'frontend-kasir/src/components/ui/card/CardContent.vue',
  'frontend-kasir/src/components/ui/card/CardDescription.vue',
  'frontend-kasir/src/components/ui/card/CardFooter.vue',
  'frontend-kasir/src/components/ui/card/CardHeader.vue',
  'frontend-kasir/src/components/ui/card/CardTitle.vue',
  'frontend-kasir/src/components/ui/card/index.ts',
  'frontend-kasir/src/components/ui/dialog/Dialog.vue',
  'frontend-kasir/src/components/ui/dialog/DialogClose.vue',
  'frontend-kasir/src/components/ui/dialog/DialogContent.vue',
  'frontend-kasir/src/components/ui/dialog/DialogDescription.vue',
  'frontend-kasir/src/components/ui/dialog/DialogFooter.vue',
  'frontend-kasir/src/components/ui/dialog/DialogHeader.vue',
  'frontend-kasir/src/components/ui/dialog/DialogOverlay.vue',
  'frontend-kasir/src/components/ui/dialog/DialogScrollContent.vue',
  'frontend-kasir/src/components/ui/dialog/DialogTitle.vue',
  'frontend-kasir/src/components/ui/dialog/DialogTrigger.vue',
  'frontend-kasir/src/components/ui/dialog/index.ts',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenu.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuContent.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuGroup.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuItem.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuLabel.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuRadioItem.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuSeparator.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuShortcut.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuSub.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuSubContent.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/DropdownMenuTrigger.vue',
  'frontend-kasir/src/components/ui/dropdown-menu/index.ts',
  'frontend-kasir/src/components/ui/empty/Empty.vue',
  'frontend-kasir/src/components/ui/empty/EmptyContent.vue',
  'frontend-kasir/src/components/ui/empty/EmptyDescription.vue',
  'frontend-kasir/src/components/ui/empty/EmptyHeader.vue',
  'frontend-kasir/src/components/ui/empty/EmptyMedia.vue',
  'frontend-kasir/src/components/ui/empty/EmptyTitle.vue',
  'frontend-kasir/src/components/ui/empty/index.ts',
  'frontend-kasir/src/components/ui/field/Field.vue',
  'frontend-kasir/src/components/ui/field/FieldContent.vue',
  'frontend-kasir/src/components/ui/field/FieldDescription.vue',
  'frontend-kasir/src/components/ui/field/FieldError.vue',
  'frontend-kasir/src/components/ui/field/FieldGroup.vue',
  'frontend-kasir/src/components/ui/field/FieldLabel.vue',
  'frontend-kasir/src/components/ui/field/FieldLegend.vue',
  'frontend-kasir/src/components/ui/field/FieldSeparator.vue',
  'frontend-kasir/src/components/ui/field/FieldSet.vue',
  'frontend-kasir/src/components/ui/field/FieldTitle.vue',
  'frontend-kasir/src/components/ui/field/index.ts',
  'frontend-kasir/src/components/ui/input/Input.vue',
  'frontend-kasir/src/components/ui/input/index.ts',
  'frontend-kasir/src/components/ui/kbd/Kbd.vue',
  'frontend-kasir/src/components/ui/kbd/KbdGroup.vue',
  'frontend-kasir/src/components/ui/kbd/index.ts',
  'frontend-kasir/src/components/ui/label/Label.vue',
  'frontend-kasir/src/components/ui/label/index.ts',
  'frontend-kasir/src/components/ui/native-select/NativeSelect.vue',
  'frontend-kasir/src/components/ui/native-select/NativeSelectOptGroup.vue',
  'frontend-kasir/src/components/ui/native-select/NativeSelectOption.vue',
  'frontend-kasir/src/components/ui/native-select/index.ts',
  'frontend-kasir/src/components/ui/pagination/Pagination.vue',
  'frontend-kasir/src/components/ui/pagination/PaginationContent.vue',
  'frontend-kasir/src/components/ui/pagination/PaginationEllipsis.vue',
  'frontend-kasir/src/components/ui/pagination/PaginationFirst.vue',
  'frontend-kasir/src/components/ui/pagination/PaginationItem.vue',
  'frontend-kasir/src/components/ui/pagination/PaginationLast.vue',
  'frontend-kasir/src/components/ui/pagination/PaginationNext.vue',
  'frontend-kasir/src/components/ui/pagination/PaginationPrevious.vue',
  'frontend-kasir/src/components/ui/pagination/index.ts',
  'frontend-kasir/src/components/ui/separator/Separator.vue',
  'frontend-kasir/src/components/ui/separator/index.ts',
  'frontend-kasir/src/components/ui/skeleton/Skeleton.vue',
  'frontend-kasir/src/components/ui/skeleton/index.ts',
  'frontend-kasir/src/components/ui/sonner/Sonner.vue',
  'frontend-kasir/src/components/ui/sonner/index.ts',
  'frontend-kasir/src/components/ui/spinner/Spinner.vue',
  'frontend-kasir/src/components/ui/spinner/index.ts',
  'frontend-kasir/src/components/ui/table/Table.vue',
  'frontend-kasir/src/components/ui/table/TableBody.vue',
  'frontend-kasir/src/components/ui/table/TableCaption.vue',
  'frontend-kasir/src/components/ui/table/TableCell.vue',
  'frontend-kasir/src/components/ui/table/TableEmpty.vue',
  'frontend-kasir/src/components/ui/table/TableFooter.vue',
  'frontend-kasir/src/components/ui/table/TableHead.vue',
  'frontend-kasir/src/components/ui/table/TableHeader.vue',
  'frontend-kasir/src/components/ui/table/TableRow.vue',
  'frontend-kasir/src/components/ui/table/index.ts',
  'frontend-kasir/src/components/ui/toggle-group/ToggleGroup.vue',
  'frontend-kasir/src/components/ui/toggle-group/ToggleGroupItem.vue',
  'frontend-kasir/src/components/ui/toggle-group/index.ts',
  'frontend-kasir/src/components/ui/toggle/Toggle.vue',
  'frontend-kasir/src/components/ui/toggle/index.ts',
  'frontend-kasir/src/composables/usePdf.ts',
  'frontend-kasir/src/composables/useScannerInput.ts',
  'frontend-kasir/src/composables/useTheme.ts',
  'frontend-kasir/src/env.d.ts',
  'frontend-kasir/src/layouts/PosLayout.vue',
  'frontend-kasir/src/lib/utils.ts',
  'frontend-kasir/src/main.ts',
  'frontend-kasir/src/pages/HistoryPage.vue',
  'frontend-kasir/src/pages/InvoicePage.vue',
  'frontend-kasir/src/pages/LoginPage.vue',
  'frontend-kasir/src/pages/PaymentPage.vue',
  'frontend-kasir/src/pages/PosPage.vue',
  'frontend-kasir/src/router/index.ts',
  'frontend-kasir/src/services/api.ts',
  'frontend-kasir/src/services/catalogApi.ts',
  'frontend-kasir/src/services/insightApi.ts',
  'frontend-kasir/src/services/memberApi.ts',
  'frontend-kasir/src/services/salesApi.ts',
  'frontend-kasir/src/stores/auth.ts',
  'frontend-kasir/src/stores/cart.ts',
  'frontend-kasir/src/style.css',
  'frontend-kasir/src/types/index.ts',
  'frontend-kasir/src/utils/format.ts'
)
$expectedByLower = @{}
foreach ($e in $expected) { $expectedByLower[$e.ToLowerInvariant()] = $e }

$root = (Get-Location).Path
$actual = foreach ($dir in 'frontend-admin/src', 'frontend-kasir/src') {
  Get-ChildItem -Path $dir -Recurse -File | ForEach-Object {
    $_.FullName.Substring($root.Length + 1).Replace('\', '/')
  }
}

$renames = @(); $stale = @()
foreach ($a in $actual) {
  $key = $a.ToLowerInvariant()
  if ($expectedByLower.ContainsKey($key)) {
    $want = $expectedByLower[$key]
    if (-not [string]::Equals($a, $want, [StringComparison]::Ordinal)) { $renames += ,@($a, $want) }
  } else { $stale += $a }
}
# Nama di index git juga bisa masih huruf lama walaupun di disk sudah benar
$tracked = git ls-files frontend-admin/src frontend-kasir/src
foreach ($t in $tracked) {
  $key = $t.ToLowerInvariant()
  if ($expectedByLower.ContainsKey($key)) {
    $want = $expectedByLower[$key]
    if (-not [string]::Equals($t, $want, [StringComparison]::Ordinal) -and -not ($renames | Where-Object { $_[0] -eq $t })) {
      $renames += ,@($t, $want)
    }
  }
}
$missing = $expected | Where-Object { -not (Test-Path -LiteralPath $_) }

Write-Host "`nGanti nama (huruf besar/kecil): $($renames.Count)" -ForegroundColor Cyan
$renames | ForEach-Object { Write-Host "  $($_[0])  ->  $($_[1])" }
Write-Host "`nFile lama yang tidak ada di repo: $($stale.Count)" -ForegroundColor Cyan
$stale | ForEach-Object { Write-Host "  $_" }
if ($missing) {
  Write-Host "`nFile repo yang TIDAK ADA di folder ini: $($missing.Count) (ekstrak ulang zip commit)" -ForegroundColor Yellow
  $missing | ForEach-Object { Write-Host "  $_" }
}
if (-not $Apply) { Write-Host "`nBelum ada yang diubah. Jalankan lagi dengan -Apply." -ForegroundColor Green; exit 0 }

foreach ($r in $renames) {
  $from, $to = $r
  $tmp = "$($to).__rename_tmp"
  $isTracked = (git ls-files -- $from) -ne $null
  if ($isTracked) { git mv -f -- $from $tmp; git mv -f -- $tmp $to }
  else { Move-Item -LiteralPath $from $tmp; Move-Item -LiteralPath $tmp $to }
}
$backup = Join-Path $env:TEMP ("kopman-file-lama-" + (Get-Date -Format 'yyyyMMdd-HHmmss'))
foreach ($s in $stale) {
  $dest = Join-Path $backup $s
  New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
  Copy-Item -LiteralPath $s $dest
  if ((git ls-files -- $s) -ne $null) { git rm -q -- $s } else { Remove-Item -LiteralPath $s }
}
# folder yang jadi kosong
foreach ($dir in 'frontend-admin/src', 'frontend-kasir/src') {
  Get-ChildItem $dir -Recurse -Directory | Sort-Object { $_.FullName.Length } -Descending |
    Where-Object { -not (Get-ChildItem $_.FullName -Force) } | Remove-Item
}
Write-Host "`nSelesai. Cadangan file lama: $backup" -ForegroundColor Green
Write-Host "Cek 'git status', lalu jalankan 'npm run build' di kedua frontend." -ForegroundColor Green
